/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/F21yGLpnwed
 */

import Image, { StaticImageData } from "next/image";

type Props = {
  src: StaticImageData
  alt?: string
  small?: boolean
}

export function RetroPhoto(props: Props) {
  const small = (props.small !== undefined) && props.small
  return (
    <div className="p-4 max-w-sm mx-auto sm:mr-auto lg:mr-10 xl:mr-15 2xl:mr-20">
      {/* <div className="bg-[#fafafa] p-6 bg-[url('https://transparenttextures.com/patterns/white-brushed.png')]"> */}
      <div className="bg-[#f7f5ed] p-6 bg-opacity-95 shadow" >
        <Image
          alt="Retro style image"
          className={props.alt ? (small ? "mb-2":"mb-5") : (small ? "mb-5":"mb-10")}
          height={small ? "200" : "400"}
          src={props.src}
          style={{
            aspectRatio: "300/300",
            objectFit: "cover",
          }}
          width={small ? "150" : "300"}
          priority
          quality={100}
        />
        <p className="text-center text-sm">{props.alt}</p>
      </div>
    </div>
  )
}
