import SiteBase from "@/components/SiteBase"
const Work = () => {
    return (
        <SiteBase title="Work">
            <div className="flex flex-col-reverse sm:flex-row items-center sm:items-start">
                {/* <p className="sm:w-[30vw]">Coming soon, watch this space.</p> */}
                <div className="flex flex-col">
                    <div className="flex flex-row items-end">
                        <p className="underline text-xl">WASHINGTON UNIVERSITY</p> <p className="">, Head Teaching Assistant</p><p className="italic">, Jan 22 - Present, St. Louis, MO</p>
                    </div>
                    <p>Led TA efforts for Advanced Machine Learning (SP24), Theory of Machine Learning (FL23-SP24), and Data Science (FL21-FL22).</p>
                    <ul className="list-disc list-inside pl-2">
                        <li>Held office hours, managed team of ~30 TAs for a ~225 student class, occassionally lectured</li>
                    </ul>
                    <div className="flex flex-row items-end">
                        <p className="underline text-xl mt-1">SQUARE</p> <p className="">, Software Engineering Intern</p><p className="italic">, June 23 - Aug 23, San Francisco, CA</p>
                    </div>
                    <p>Designed and revitalized high throughput critical infrastructure for Square Banking.</p>
                    <ul className="list-disc list-inside pl-2">
                        <li>Pioneered effort to deconstruct legacy service Ledger, responsible for all balance tracking at Square</li>
                        <li>Led an intern hack week team to develop an internal AI service-specific research agent, using entirely local LLMs (Nous-Hermes-Llama2-13b) and RAG with a handrolled vector DB</li>
                    </ul>
                    <div className="flex flex-row items-end">
                        <p className="underline text-xl mt-1">WINTICS</p> <p className="">, ML Engineering Intern</p><p className="italic">, February 23 - Apr 23, Paris, France</p>
                    </div>
                    <p>Trained computer vision models to generate analytics for Smart Cities.</p>
                    <ul className="list-disc list-inside pl-2">
                        <li>Used MaskRCNN for boundary detection and ConvNeXT for classification of pedestrian clothing type and coloration, deploying both to embedded devices on client cameras</li>
                        <li>All work done in French</li>
                    </ul>
                    <div className="flex flex-row items-end">
                        <p className="underline text-xl mt-1">MICROSOFT</p> <p className="">, ML Engineering Intern</p><p className="italic">, June 22 - Aug 22, Seattle, WA</p>
                    </div>
                    <p>Researched and implemented methods for anomaly detection in high-dimensional time series data generated by large scale distributed systems.</p>
                    <ul className="list-disc list-inside pl-2">
                        <li>Pioneered ML work for the Athena team with the goal of diagnosis and prognosis of anomalies within the Azure cloud, and detecting outages before they occur (recently patented!)</li>
                        <li>First place team at the annual intern Puzzle Hunt (à la MIT Mystery Hunt) out of 1300 entrants</li>
                    </ul>
                    <div className="flex flex-row items-end">
                        <p className="underline text-xl mt-1">4GIVING</p> <p className="">, Software Development Intern</p><p className="italic">, June 21 - Aug 21, Minneapolis, MN</p>
                    </div>
                    <p>Revamped onboarding for client non-profits to automate profile and first fundraiser creation with AI.</p>
                    <ul className="list-disc list-inside pl-2">
                        <li>Developed full stack webapp, using company mission statements, social media and other sources as input to a fine-tuned GPT3 to generate target fundraiser samples specific to the organization</li>
                    </ul>
                </div>
                
                {/* <div className="flex-1">
                <RetroPhoto src={mountains} /> 
                </div> */}
            </div>
        </SiteBase>
    )
}

export default Work