import SiteBase from "@/components/SiteBase"
import { fullName } from "@/lib/content"
import useIsMobile from "@/lib/utils"

type Position = {
    company: string,
    title: string,
    location: string,
    dates: string,
    description: string,
    bullets?: string[]
}

const positions: Position[] = [
    {
        company: "INDEPENDENT RESEARCHER",
        title: "",
        location: "San Francisco, CA",
        dates: "Apr '25 - Present",
        description: "Working on a variety of research and engineering projects, as well as consulting on AI / LLMs.",
        bullets: [
        ]
    },
    {
        company: "ADVEX AI",
        title: "Founding ML Engineer",
        location: "San Francisco, CA",
        dates: "Dec '24 - Mar '25",
        description: "Generated high quality synthetic data (images / masks) using diffusion models to solve low data regime / out-of-distribution computer vision tasks.",
        bullets: [
            "Owned engineering and research initiatives across the entire pipeline, from better LoRA training for SDXL to automated captioning with VLMs to deployment infrastructure to full stack development of the self-serve platform",
            "Successfully delivered self-serve and bespoke offerings to clients, including multi billion dollar companies in logistics and manufacturing in the US and abroad"
        ]
    },
    {
        company: "THERAP SERVICES",
        title: "Member of Technical Staff, AI Research",
        location: "Remote",
        dates: "Jul '24 - Present",
        description: "Directed AI strategy and research initiatives at a leading electronic health record (EHR) provider.",
        bullets: [
            "Researched and prototyped a variety of AI-based solutions for the Therap platform, including fine-tuning LLMs for secure deployment at enterprise scale, and an on-camera VLM based event log system -- both under patent review",
            "Advised ML research and engineering teams on applied projects, and traveled to Bangladesh with the C-suite to oversee division restructuring to modernize AI strategy"    
        ]
    },
    {
        company: "WASHINGTON UNIVERSITY",
        title: "Head Teaching Assistant",
        location: "St. Louis, MO",
        dates: "Jan '22 - May '24",
        description: "Led TA efforts for Advanced Machine Learning (SP24), Theory of Machine Learning (FL23-SP24), and Data Science (FL21-FL22).",
        bullets: [
            "Held office hours, managed team of ~30 TAs for a ~225 student class, reworked curriculum, occassionally lectured; received departmental award for excellence",
        ]
    },
    {
        company: "SQUARE",
        title: "Software Engineering Intern",
        location: "San Francisco, CA",
        dates: "June '23 - Aug '23",
        description: "Designed and revitalized high throughput critical infrastructure for Square Banking.",
        bullets: [
            "Pioneered effort to deconstruct legacy service responsible for all balance tracking at Square, designed new architecture and data model",
            "Led an intern hack week team to develop an internal AI service-specific research agent, using entirely local LLMs (Nous-Hermes-Llama2-13b) and RAG with a handrolled vector DB"
        ]
    },
    {
        company: "WINTICS",
        title: "ML Engineering Intern",
        location: "Paris, France",
        dates: "February '23 - Apr '23",
        description: "Trained on-camera computer vision models to generate analytics for Smart Cities.",
        bullets: [
            "MaskRCNN / ConvNeXT for real-time boundary detection / classification of pedestrians, cyclists, etc in frame as well as clothing type and coloration. Deployed to embedded devices on client cameras (PyTorch, ONNX, TensorRT), including use at the Paris Olympics",
            "All work done in French"
        ]
    },
    {
        company: "MICROSOFT",
        title: "ML Engineering Intern",
        location: "Seattle, WA",
        dates: "June '22 - Aug '22",
        description: "Researched and implemented deep learning methods for anomaly detection in high-dimensional time series data generated by large scale distributed systems.",
        bullets: [
            "Pioneered ML work for the Athena team to diagnose anomalies within the Azure cloud, detecting outages before they occur and finding the root cause (patented)",
            "Trained novel graph attention model to process 10,000+ time-series emitted per team (.95 F1), and deployed end-to-end pipeline in Azure ML to client teams",
            "First place team at the annual intern Puzzle Hunt (à la MIT Mystery Hunt) out of 1300 entrants"
        ]
    },
    {
        company: "4GIVING",
        title: "Software Development Intern",
        location: "Minneapolis, MN",
        dates: "June '21 - Aug '21",
        description: "Created an AI agent to generate first fundraisers and automate profile creation for client non-profits.",
        bullets: [
            "Fine-tuned GPT3 with existing platform data to create sample fundraisers (titles and descriptions), using web-scraping to effectively prompt the model with non-profit info (e.g. mission statement, social media, etc)",
            "Developed full stack webapp to package the experience and make onboarding seamless"
        ]
    }
]

const Work = () => {
    const isMobile = useIsMobile(640)
    return (
        <SiteBase title="Work" description={`${fullName}'s personal website work history page`}>
            <div className="flex flex-col-reverse sm:flex-row items-center sm:items-start">
                <div className="flex flex-col">
                    {positions.map((position: Position) => {
                        return (
                            <div key={position.company + position.title + position.dates}>
                                <div className="flex flex-col sm:flex-row sm:items-end">
                                    <p className="underline text-xl mt-1">{position.company}</p> <p className="">{!isMobile && position.title && ","} {position.title}</p><p className="italic">{!isMobile && position.location && ","} {position.dates}, {position.location}</p>
                                </div>
                                <p>{position.description}</p>
                                <ul className="list-disc list-inside pl-2">
                                    {position.bullets?.map((bullet: string) => {
                                        return (
                                            <li key={bullet}>{bullet}</li>
                                        )
                                    })}
                                </ul>
                            </div>
                        )
                    })}
                </div>
            </div>
        </SiteBase>
    )
}

export default Work