import SiteBase from "@/components/SiteBase"
import { fullName } from "@/lib/content"
import useIsMobile from "@/lib/utils"

type Position = {
    company: string,
    title: string,
    location: string,
    dates: string,
    description: string,
    bullets?: string[]
}

const positions: Position[] = [
    {
        company: "WASHINGTON UNIVERSITY",
        title: "Head Teaching Assistant",
        location: "St. Louis, MO",
        dates: "Jan '22 - May '24",
        description: "Led TA efforts for Advanced Machine Learning (SP24), Theory of Machine Learning (FL23-SP24), and Data Science (FL21-FL22).",
        bullets: [
            "Held office hours, managed team of ~30 TAs for a ~225 student class, reworked curriculum, occassionally lectured"
        ]
    },
    {
        company: "SQUARE",
        title: "Software Engineering Intern",
        location: "San Francisco, CA",
        dates: "June '23 - Aug '23",
        description: "Designed and revitalized high throughput critical infrastructure for Square Banking.",
        bullets: [
            "Pioneered effort to deconstruct legacy service responsible for all balance tracking at Square, designed new architecture and data model (Java, Kotlin, tRPC)",
            "Led an intern hack week team to develop an internal AI service-specific research agent, using entirely local LLMs (Nous-Hermes-Llama2-13b) and RAG with a handrolled vector DB"
        ]
    },
    {
        company: "WINTICS",
        title: "ML Engineering Intern",
        location: "Paris, France",
        dates: "February '23 - Apr '23",
        description: "Trained computer vision models to generate analytics for Smart Cities.",
        bullets: [
            "MaskRCNN / ConvNeXT for real-time boundary detection / classification of pedestrians, cyclists, etc in frame as well as clothing type and coloration. Deployed to embedded devices on client cameras (PyTorch, ONNX, TensorRT)",
            "All work done in French"
        ]
    },
    {
        company: "MICROSOFT",
        title: "ML Engineering Intern",
        location: "Seattle, WA",
        dates: "June '22 - Aug '22",
        description: "Researched and implemented deep learning methods for anomaly detection in high-dimensional time series data generated by large scale distributed systems.",
        bullets: [
            "Pioneered ML work for the Athena team with the goal of diagnosis and prognosis of anomalies within the Azure cloud, and detecting outages before they occur (recently patented!)",
            "Novel graph attention network architecture, deployed end-to-end pipeline in Azure ML to client teams",
            "First place team at the annual intern Puzzle Hunt (à la MIT Mystery Hunt) out of 1300 entrants"
        ]
    },
    {
        company: "4GIVING",
        title: "Software Development Intern",
        location: "Minneapolis, MN",
        dates: "June '21 - Aug '21",
        description: "Revamped onboarding for client non-profits to automate profile and first fundraiser creation with AI.",
        bullets: [
            "Developed full stack webapp, using company mission statements, social media and other sources as input to a fine-tuned GPT3 to generate target fundraiser samples specific to the organization"
        ]
    }
]

const Work = () => {
    const isMobile = useIsMobile(640)
    return (
        <SiteBase title="Work" description={`${fullName}'s personal website work history page`}>
            <div className="flex flex-col-reverse sm:flex-row items-center sm:items-start">
                <div className="flex flex-col">
                    {positions.map((position: Position) => {
                        return (
                            <div key={position.company + position.title + position.dates}>
                                <div className="flex flex-col sm:flex-row sm:items-end">
                                    <p className="underline text-xl mt-1">{position.company}</p> <p className="">{!isMobile && ","} {position.title}</p><p className="italic">{!isMobile && ","} {position.dates}, {position.location}</p>
                                </div>
                                <p>{position.description}</p>
                                <ul className="list-disc list-inside pl-2">
                                    {position.bullets?.map((bullet: string) => {
                                        return (
                                            <li key={bullet}>{bullet}</li>
                                        )
                                    })}
                                </ul>
                            </div>
                        )
                    })}
                </div>
            </div>
        </SiteBase>
    )
}

export default Work